apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: vidhyadevops/webimage
        ports:
        - containerPort: 80
